<?php


namespace SIGA\Http\Controllers;


use SIGA\Acl\Repositories\RoleRepository;
use SIGA\Acl\Role;
use SIGA\Http\AbstractController;
use SIGA\Http\Requests\RoleRequest;

class RoleController extends AbstractController
{
    protected $prefix = '';
    protected $template ='roles';
    protected $model = Role::class;
    protected $repository = RoleRepository::class;

    public function store(RoleRequest $request)
    {
        return parent::storeBy($request);
    }

    public function update(RoleRequest $request, $id)
    {
        return parent::updateBy($request, $id); // TODO: Change the autogenerated stub
    }
}
